// Full `JamPlayer` surface so a test never has to enumerate the methods it needs.
export const JamPlayer = {
	shuffleQueueSync: jest.fn(),
	shuffleQueue: jest.fn(async (): Promise<void> => undefined),
	clearQueueSync: jest.fn(),
	clearQueue: jest.fn(async (): Promise<void> => undefined),
	addTrackToQueue: jest.fn(async (): Promise<void> => undefined),
	removeTrackFromQueue: jest.fn(async (): Promise<void> => undefined),
	addTracksToQueue: jest.fn(async (): Promise<void> => undefined),
	playTrack: jest.fn(async (): Promise<void> => undefined),
	playTracks: jest.fn(async (): Promise<void> => undefined),
	skipToTrack: jest.fn(async (): Promise<void> => undefined),
	skipBackwardSync: jest.fn(),
	skipBackward: jest.fn(async (): Promise<void> => undefined),
	play: jest.fn(async (): Promise<void> => undefined),
	toggleSync: jest.fn(),
	toggle: jest.fn(async (): Promise<void> => undefined),
	stop: jest.fn(async (): Promise<void> => undefined),
	destroy: jest.fn(async (): Promise<void> => undefined),
	pause: jest.fn(async (): Promise<void> => undefined),
	skipForwardSync: jest.fn(),
	skipForward: jest.fn(async (): Promise<void> => undefined),
	skipToNextSync: jest.fn(),
	skipToNext: jest.fn(async (): Promise<void> => undefined),
	skipToPreviousSync: jest.fn(),
	skipToPrevious: jest.fn(async (): Promise<void> => undefined),
	seekPercent: jest.fn(async (): Promise<void> => undefined),
	seekPercentSync: jest.fn(),
	setVolume: jest.fn(async (): Promise<void> => undefined)
};
