name: build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
      - uses: actions/checkout@v2

      - name: Envinfo
        run: npx envinfo

      - name: Install Dependencies
        run: yarn install

      - name: Jettify
        run: npx jetify

      - name: Gradle chmod Setup
        run: cd android && chmod +x gradlew

      - name: Build application apks
        run: cd android && ./gradlew assembleRelease

      - name: Build application aab
        run: cd android && ./gradlew bundleRelease
